# Generated by Django 2.2.3 on 2019-12-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0005_auto_20191203_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servertype',
            name='zctype',
            field=models.CharField(max_length=20, unique=True, verbose_name='资产类型'),
        ),
    ]
