# Generated by Django 2.2.3 on 2019-12-03 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0006_auto_20191203_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='undernet',
        ),
    ]
