# Generated by Django 2.2.3 on 2019-12-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0008_servertype_modify_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='undernet',
            field=models.CharField(default='闲置', max_length=10, verbose_name='所在网络'),
        ),
    ]
